### ISSUE TITLE
Program

### ISSUE THREAD

**Issue by Ianmm17** [lucthesloth/maplink#1]
Is this program still supported? If so will this work on a dual pc setup?

**Comment by lucthesloth** [comment]
It's still in use by some Rust streamers. It is focused on 2 pc setups.

You can keep this issue open in case if you have difficulties using it.

**Comment by Ianmm17** [comment]
How exactly should this program be setup? I’ve downloaded all the programs but I’m having issues setting it up. Should map link live on the gaming pc and connect to streaming pc?

**Comment by lucthesloth** [comment]
> How exactly should this program be setup? I’ve downloaded all the programs but I’m having issues setting it up. Should map link live on the gaming pc and connect to streaming pc?

Maplink is ran on the gaming pc, it connects over to the streaming pc using obs websockets.
Make sure you have dotnet framework installed

**Comment by Ianmm17** [comment]
Okay, I haven’t checked that, dotnet should be installed on which pc? Also when maplink says ip to connect to I would assume it’s the ipconfig ip on the streaming pc and not the 127.0.0.1 default correct?

**Comment by lucthesloth** [comment]
> Okay, I haven’t checked that, dotnet should be installed on which pc? Also when maplink says ip to connect to I would assume it’s the ipconfig ip on the streaming pc and not the 127.0.0.1 default correct?

Yes, the ip for  the streaming pc alongside the password.
Dotnet runs on the computer maplink is running

**Comment by lucthesloth** [comment]
> > Okay, I haven’t checked that, dotnet should be installed on which pc? Also when maplink says ip to connect to I would assume it’s the ipconfig ip on the streaming pc and not the 127.0.0.1 default correct?
> 
> Yes, the ip for the streaming pc alongside the password. Dotnet runs on the computer maplink is running

Password to obs websocket

**Comment by Ianmm17** [comment]
Thank you, I will try installing dotnet. I appreciate the quick response

**Comment by Ianmm17** [comment]
installing dotnet fixed it, thank you!
