### ISSUE TITLE
Can't Get WebSocket to Connect

### ISSUE THREAD

**Issue by ColorDumper** [lucthesloth/maplink#3]
After reinstalling windows on both of my pcs I'm unable to get maplink to connect to my OBS studio. I have installed dotnet framework, OBS WebSocket 4.9.1 (running OBS 30.2.3). I'm really confused because before this app would run flawlessly.

**Comment by lucthesloth** [comment]
Hey there @ColorDumper, I'm happy to help you with troubleshooting this.
Are you using it locally on the same computer as OBS or is it over the network?
Any specific error message from within the app in the log section? Timeout or cannot reach host?

**Comment by ColorDumper** [comment]
Hi, I'm using the app on my gaming pc, and trying to connect it through OBS WebSocket to my streaming pc. I keep getting OBS Connection Error.

**Comment by lucthesloth** [comment]
Can you let me know the following:
The IP assignment in your local network is the same as is set in the app?
Firewall ports are open either in windows or you firewall utility in the streaming pc?
OBS' socket is active in streaming pc? Password matches the one set in the app?

**Comment by ColorDumper** [comment]
Thanks for responding quickly. It was the port in my firewall, had  to open it and now it's working again. Thanks!

**Comment by lucthesloth** [comment]
No problem, glad I could help 🦥
